### ISSUE TITLE
Can't seem to get resolution on #27

### ISSUE THREAD

**Issue by Brantlab** [huyb1991/hugo-lamp#51]
I am trying to use Yawn or NPM just to update the theme. I get this when I run `Yarn watch`
```
PS C:\Repos\Testing\themes\hugo-lamp> yarn watch
yarn run v1.17.3
$ nodemon -e scss -w ./ -x npm run build
[nodemon] 1.19.2
[nodemon] to restart at any time, enter `rs`
[nodemon] watching dir(s): **\*
[nodemon] starting `npm run build`

> hugo-lamp@1.0.2 build C:\Repos\Testing\themes\hugo-lamp
> node ./index.js

internal/modules/cjs/loader.js:775
    throw err;
    ^

Error: Cannot find module 'node-sass'
Require stack:
- C:\Repos\Testing\themes\hugo-lamp\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:772:15)
    at Function.Module._load (internal/modules/cjs/loader.js:677:27)
    at Module.require (internal/modules/cjs/loader.js:830:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (C:\Repos\Testing\themes\hugo-lamp\index.js:4:14)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:999:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'C:\\Repos\\Testing\\themes\\hugo-lamp\\index.js' ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hugo-lamp@1.0.2 build: `node ./index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hugo-lamp@1.0.2 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\SimplyTech\AppData\Roaming\npm-cache\_logs\2019-09-06T19_03_00_335Z-debug.log
[nodemon] app crashed - waiting for file changes before starting...
```

Then if I try running `yarn build`

```
PS C:\Repos\Testing\themes\hugo-lamp> yarn build
yarn run v1.17.3
$ node ./index.js
internal/modules/cjs/loader.js:775
    throw err;
    ^

Error: Cannot find module 'node-sass'
Require stack:
- C:\Repos\Testing\themes\hugo-lamp\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:772:15)
    at Function.Module._load (internal/modules/cjs/loader.js:677:27)
    at Module.require (internal/modules/cjs/loader.js:830:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (C:\Repos\Testing\themes\hugo-lamp\index.js:4:14)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:999:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'C:\\Repos\\Testing\\themes\\hugo-lamp\\index.js' ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by huyb1991** [comment]
@Brantlab It's seem something wrong when install `node-sass`, could you try to install it after run `npm install` or `yarn install`.

Let's try `yarn add -D node-sass` or `npm install --save-dev node-sass`

**Comment by Brantlab** [comment]
Stopped working on this and haven't come back around to it.
